theme = "catppuccin_mocha"

[editor]
line-number = "relative"
default-line-ending = "lf"
popup-border = "all"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.cursor-shape]
normal = "block"
insert = "block"
select = "block"

[editor.auto-save]
focus-lost = false
after-delay.enable = false
after-delay.timeout = 5000

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 40
wrap-indicator = ""
wrap-at-text-width = false

