[[manager.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "chmod on selected files"

[[manager.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "diff the selected file with the hovered file"

[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block --confirm'
desc = "open shell here"

[[manager.prepend_keymap]]
on   = "<C-n>"
run  = 'shell "ripdrag "$@" -x 2>/dev/null &" --confirm'
desc = "drag and drop on selected files"

[[manager.prepend_keymap]]
on   = [ "g", "r" ]
run  = '''
    shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
'''
desc = "back to the root of the current git repository"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin --sync max-preview"
desc = "maximize or restore preview"
